config/routes.rb
Rails.application.routes.draw do
  root to: 'application#home'
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}
  devise_scope :user do 
    get 'login', to: 'devise/session#new'
    get 'signup', to: 'devise/registration#new'
  end
  get '/products/search', to: 'products#search', as: 'products_search'
  get 'products/expensive', to: 'products#expensive', as: 'products_expensive'
  resources :products
  
  resources :categories do 
    resources :categories, only: [:index, :new, :show]
    resources :products, only: [:index, :new, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    has_many :users, through: :products 

    #accepts_nested_attributes_for :products, reject_if: :all_blank

   validates :title, presence: true, uniqueness:true
   

   
    scope :search_category, ->(category_search) { where("title LIKE ?", "%#{category_search}%") }

    def product_name 
        self.products.map do |product| 
        product.name
        end 
    end 
end

app/models/product.rb
class Product <  ApplicationRecord
   belongs_to :category, optional: true
   belongs_to :user, optional: true

   accepts_nested_attributes_for :category, reject_if: :all_blank
     validates :name, presence: true, uniqueness:true
     validates :description, presence: true
     validates :price, presence: true
     validates :category, presence: true

     scope :searched, ->(search_term) { where("name LIKE ?", "%#{search_term}%") }
     scope :expensive, ->{ where("price > 50")} 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products
  has_many :categories, through: :products
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true
  validates :username, presence: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

         def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.provider = auth.provider
            user.username = auth.info.name 
            user.uid = auth.uid 
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
        end
      end
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def home 
    end 
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        @user=User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end 
end 

app/controllers/categories_controller.rb
class CategoriesController < ProductsController
    before_action :authenticate_user!
    def index 
        if params[:search]
            @categories = Category.search_category(params[:search])
        else
            @categories = Category.all.order(:title) 
    end 
end
    def show 
        @category = Category.find(params[:id])
    end 
    def new 
        @category = Category.new
    end 
    def edit 
        @category = Category.find(params[:id])
    end 
    def create 
        @category = Category.new(category_params)
        if  @category.save 
            redirect_to categories_path, notice: "Category Successfully Created"
        else 
            render 'new'
        end 
    end 
    def update 
        @category = Category.find(params[:id])
        if @category.update(category_params)
            redirect_to category_path(@category), notice: "category Successfully Updated" 
        else 
            render :edit 
        end
    end
    def destroy 
        @category = Category.find(params[:id]).destroy
        redirect_to categories_path
    end 
    private 
    def category_params
        params.require(:category).permit(:title, products_attributes: [:name] )
    end 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    #before_action :set_product, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    def index 
        if params[:search]
           
                @products = Product.searched(params[:search])
            else
                @products = Product.all.order(:category_id) 
        end 
        
    end 
    def show 
        @product = Product.find(params[:id])
    end 
    def new 
        @product = Product.new
    end 
    def edit 
        @product = Product.find(params[:id])
    end 
    def create 
        @product = Product.new(product_params)
        if  @product.save 
            redirect_to product_path(@product), notice: "Product Successfully Created"
        else 
            render 'new'
        end 
    end 
    def destroy 
        @product = Product.find(params[:id]).destroy
        redirect_to products_path
    end 
    def update 
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to product_path(@product), notice: "product Successfully Updated" 
        else 
            render :edit 
        end
    end
    def expensive 
        @products = Product.expensive
        render :index
    end

    private 
    def product_params
        params.require(:product).permit(:name, :description, :price, :user_id, :category_id, category_attributes: [:title])
    end 
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private 

    def sign_up_params 
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end 
    def account_update_params 
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/application/home.html.erb
<h1>Queen Workx</h1>
<% Product.all.each do |product| %>
Category:    <%= product.category.title %><br>
Name: <%= link_to product.name, product %> <br>
Description: <%= product.description %> <br>
Price : $ <%= product.price %> <br> <br>
<% end %>

app/views/categories/edit.html.erb
<% if @category.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
  <ul>
  <% @category.errors.full_messages.each do |msg| %>
    <li><%= msg %></li> <br>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_for(@category) do |f| %>
    
    <%= f.label :new_category_title %>
    <%= f.text_field :title %> <br>
    <%=f.submit %>
    
  <% end %>

  <style>
  li {
    color: red;
    font-weight: bold;
  }
</style>

app/views/categories/index.html.erb
<h1>Search Categories</h1>
<h4>
<%= form_tag categories_path, :method => 'get' do %>   
    <%= text_field_tag :search, params[:search] %>   
    <%= submit_tag "Search", name: nil %> </h4>
<% end %>
<br>
<%= link_to 'Create Category', new_category_path %><br> <br>
<% @categories.each do |category| %>
    <h3><%= link_to category.title, category %>
    <%= link_to "Edit", edit_category_path(category) %>
    <%= link_to "Delete", category_path(category), method: :delete, class: "destroy", data: {confirm: "Are you sure?"} %></h3>
    
    Products: <%= category.product_name %><br><br>
    
<%end%>

app/views/categories/new.html.erb
<% if @category.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
  <ul>
  <% @category.errors.full_messages.each do |msg| %>
    <li><%= msg %></li> <br>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_for(@category) do |f| %>
    
    <%= f.label :new_category_title %>
    <%= f.text_field :title %> <br>
    <%=f.submit %>
    
  <% end %>
  <style>
        li {
          color: red;
          font-weight: bold;
        }
</style>

app/views/categories/search.html.erb
<h1>Search Categories</h1>
<h4>
<%= form_tag categories_path, :method => 'get' do %>   
    <%= text_field_tag :search, params[:search] %>   
    <%= submit_tag "Search", name: nil %> </h4>
<% end %>

app/views/categories/show.html.erb
<%= @category.title %> <br>
Products: <%= @category.product_name %>

app/views/layouts/_nav.html.erb
<nav> 
    <ul>
    <li><%= link_to "Home", root_path %></li>
    <% if !user_signed_in? %>
        <li><%= link_to "Signup", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
    <% else %>
        
    <div class="dropdown">
    <button class="dropbtn"> 
    <li><%= link_to "Categories", categories_path %></li>
      <i class="fa fa-caret-down"></i>
    </button>
      <div class="dropdown-content">
      <a href="../categories/1">Body collection</a>
      <a href="../categories/2">Hair collection</a>
      <a href="../categories/3">Wellness collection</a>
      </div>
    </div> 
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method:"delete" %></li>
        <li>WELCOME!! <%= current_user.username %></li><br>
        <li><%= current_user.email %></li>
        <% end %>
    </ul>
</nav>

<style>
body {
  background-image: url('https://i.pinimg.com/originals/90/93/ed/9093ed6b9cda1cfa683ade4549a9feaa.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
  background-position:center;
  
 
}
nav ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: black;
}
nav li {
  float: left;
  color: gold;
}

nav li a {
  display: block;
  color: gold;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}
nav li a:hover {
  background-color: #555;
}
.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: gold;

  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.dropdown:hover .dropbtn {
  background-color: #555;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}
.i
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Queenworkx.com</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    </head>

  <body>
  <%= render 'layouts/nav' %>
    <%= yield %>
    
  </body>
</html>

app/views/products/edit.html.erb
<% if @product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

  <ul>
  <% @product.errors.full_messages.each do |msg| %>
    <li><%= msg %></li> <br>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_for(@product) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>
    <%= f.label :description %>
    <%= f.text_field :description %> <br>
    <%= f.label :price %> 
    <%= f.text_field :price %> <br>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all.order(:title), :id, :title, include_blank: true %><br><br>
    <%=f.submit %>
        
<% end %>

<style>
    li {
      color: red;
      font-weight: bold;
    }
</style>
   

app/views/products/expensive.html.erb
<h1> expensive </h1>
<% @products.each do |product| %>
 Name:   <%= product.name %> <br>
 Price: $ <%= product.price %> <br> <br>
<%end %>

app/views/products/index.html.erb
<h4>Search Products</h4>

<%= form_tag products_path, :method => 'get' do %>   
    <%= text_field_tag :search, params[:search] %>   
    <%= submit_tag "Search", name: nil %> </h4>
<% end %>
<br>
<%= link_to "Expensive Products" , products_expensive_path %>
<br>

<h1>All Products</h1>
<%= link_to 'Create Product', new_product_path %><br> <br>

<h3>Items sorted by category</h3>
<% @products.each do |product| %>
    
    <%= link_to product.name, product %><br>
    <%= link_to "Delete", product_path(product), method: :delete, class: "destroy", data: {confirm: "Are you sure?"} %><br>
    <%= link_to "Edit", edit_product_path(product) %><br><br>
   
    <% end %>

app/views/products/new.html.erb
<% if @product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

  <ul>
  <% @product.errors.full_messages.each do |msg| %>
    <li><%= msg %></li> <br>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_for(@product) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>
    <%= f.label :description %>
    <%= f.text_field :description %> <br>
    <%= f.label :price %> 
    <%= f.text_field :price %> <br>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all.order(:title), :id, :title, include_blank: true %><br><br>
    <%=f.submit %>
        
      <% end %>
<style>
    li {
      color: red;
      font-weight: bold;
    }
</style>
   
   
   
    

app/views/products/search.html.erb
<h1>Search Products</h1>
<h4>
<%= form_tag products_path, :method => 'get' do %>   
    <%= text_field_tag :search, params[:search] %>   
    <%= submit_tag "Search", name: nil %> </h4>
<% end %>

app/views/products/show.html.erb
<h4>Category: <%= @product.category.title %> <br>
Name: <%= @product.name %> <br>
Description: <%= @product.description %> <br>
Price : $ <%= @product.price %> <br>
<%= link_to "Delete", product_path(@product), method: :delete, class: "destroy", data: {confirm: "Are you sure?"} %>
<%= link_to "Edit", edit_product_path(@product) %></h4>